name: Build Test Check
on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Use custom NuGet build test check action
        uses: SURIMI-Project/Surimi-GithubActions/BuildTestCheckUbuntuBSR@master
        with:
          bsr-token: ${{ secrets.BSR_TOKEN }}
